
name : run python script 
on: 
  push 

jobs:
  printing-python:
    runs-on: ubuntu-latest

    steps:
      - name: clone-repo
        uses: actions/checkout@v5

      - name: setting up python
        uses: actions/setup-python@v6
        with:
            python-version: '3.13' 
      - name: Install pandas
        run: pip install pandas
  
      - name: Run Python script
        run: python Self_Preparation/Pandasssss/5.py

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.google.com
          # Optional port (defaults to 465)
          port: 587
          secure: true
          account: ${v07e01l99@gmail.com}
          password: ${asdfghjkl@123}
          sender: vel
          from: v07e01l99@gmail.com
          to: v07e01l99@gmail.com
          subject: Job Trigger in git hub.
          body: your messages.
          ignore_cert: true
          convert_markdown: true
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'
