
name : run python script 
on: 
  push 

jobs:
  printing-python:
    runs-on: ubuntu-latest

    steps:
      - name: clone-repo
        uses: actions/checkout@v5

      - name: setting up python
        uses: actions/setup-python@v6
        with:
            python-version: '3.13' 
      - name: Install pandas
        run: pip install pandas
  
      - name: Run Python script
        run: python Self_Preparation/Pandasssss/5.py

      - name: Send email
        uses: devellany/send-mailer@v1.0.2
        with:
          host: smtp.google.com
        # Optional port (defaults to 465)
          port: 465
          account: ${v07e01l99@gmail.com}
          password: ${{Asdfghjkl@123}}
          sender: vel
          from: ${v07e01l99@gmail.com}
          to: velmuruganvaradharajan07@gmail.com
          subject: Job Trigger in git hub.
          body: your messages.
          # Optional content type (defaults to text/plain)
          contentType: text/plain
          # Optional attachment files (JSON type. require property 'path')
          attachments: '[{"path":"README.md"}]'
