
name : run python script 
on: 
  push 

jobs:
  printing-python:
    runs-on: ubuntu-latest

    steps:
      - name: clone-repo
        uses: actions/checkout@v5

      - name: setting up python
        uses: actions/setup-python@v6
        with:
            python-version: '3.13' 
      - name: Install pandas
        run: pip install pandas
  
      - name: Run Python script
        run: python Self_Preparation/Pandasssss/5.py
