
name : run python script 
on: 
  push 

jobs:
  printing-python:
    runs-on: ubuntu-latest

    steps:
      - name: clone-repo
        uses: actions/checkout@v5

      - name: setting up python
        uses: actions/setup-python@v6
        with:
            python-version: '3.13' 
  
      - name: Run Python script
        run: C:\Users\VV1205\OneDrive - Hitachi Energy\Desktop\Velmurugan\Learnings\Python_Projects\pythonprojects\Self_Preparation\voice_Code\voicereg.pypython voicereg.py
   
